kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-declaration
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.10.0",
        "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
        "label": "Sample 4",
        "remark": "Simple HTTP application with RR pool",
        "AS3": {
          "class": "Tenant",
          "A4": {
            "class": "Application",
            "template": "https",
            "serviceMain": {
              "class": "Service_HTTPS",
              "virtualAddresses": [
                "10.192.75.104"
              ],
              "pool": "https_pool"
            },
            "https_pool": {
              "class": "Pool",
              "monitors": [
                "https"
              ],
              "members": [
                {
                  "servicePort": 443,
                  "serverAddresses": []
                }
              ]
            }
          }
        }
      }
    }
