kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-declaration
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.10.0",
        "id": "1847a369-5a25-4d1b-8cad-5740988d4423",
        "label": "Sample AS3 Template",
        "remark": "HTTPs application",
        "stark": {
          "class": "Tenant",
          "blog": {
            "class": "Application",
            "template": "http",
            "serviceMain": {
              "class": "Service_HTTP",
              "virtualAddresses": [
                "10.192.75.104"
              ],
              "virtualPort": 443,
              "pool": "https_pool"
            },
            "https_pool": {
              "class": "Pool",
              "monitors": [
                "https"
              ],
              "members": [
                {
                  "servicePort": 443,
                  "serverAddresses": []
                }
              ]
            }
          }
        }
      }
    }
