kind: ConfigMap
apiVersion: v1
metadata:
  name: pepsi-as3-template
  namespace: default
  labels:
    f5type: virtual-server
    as3: true
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.0.0",
        "id": "fghijkl7890",
        "label": "Pepsi Blog Declaration",
        "remark": "HTTP two applications",
        "pepsi": {
          "class": "Tenant",
          "blog": {
            "class": "Application",
            "template": "http",
            "serviceMain": {
              "class": "Service_HTTP",
              "virtualAddresses": [
                "10.0.6.100"
              ],
              "pool": "web_pool"
            },
            "serviceDB": {
              "class": "Service_TCP",
              "template": "tcp",
              "virtualAddress": [
                "10.0.7.100"
              ],
              "pool": "db_pool"
            },
            "db_pool": {
              "class": "Pool",
              "members": [
                {
                  "servicePort": 3306,
                  "serverAddresses": [
                    "192.0.7.10",
                    "192.0.7.11"
                  ]
                }
              ]
            },
            "web_pool": {
              "class": "Pool",
              "monitors": [
                "http"
              ],
              "members": [
                {
                  "servicePort": 80,
                  "serverAddresses": [
                    "192.0.6.10",
                    "192.0.6.11"
                  ]
                }
              ]
            }
          }
        }
      }
    }