kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-declaration
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.10.0",
        "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
        "label": "Sample 1",
        "remark": "Simple HTTP application with RR pool",
        "AS3": {
          "class": "Tenant",
          "A1": {
            "class": "Application",
            "template": "http",
            "serviceMain": {
              "class": "Service_HTTP",
              "virtualAddresses": [
                "10.192.75.101"
              ],
              "pool": "web_pool"
            },
            "web_pool": {
              "class": "Pool",
              "monitors": [
                "http"
              ],
              "members": [
                {
                  "servicePort": 80,
                  "serverAddresses": []
                }
              ]
            }
          },
          "A3": {
            "class": "Application",
            "template": "http",
            "serviceMain": {
              "class": "Service_HTTP",
              "virtualAddresses": [
                "10.192.75.99"
              ],
              "pool": "waf_pool",
              "policyEndpoint": "forward_policy",
              "securityLogProfiles": [
                {
                  "bigip": "/Common/Log all requests"
                }
              ],
              "policyWAF": {
                "use": "OWASPAutoTune"
              }
            },
            "forward_policy": {
              "class": "Endpoint_Policy",
              "rules": [
                {
                  "name": "forward_to_pool",
                  "conditions": [
                    {
                      "type": "httpUri",
                      "path": {
                        "operand": "contains",
                        "values": [
                          "admin"
                        ]
                      }
                    }
                  ],
                  "actions": [
                    {
                      "type": "httpRedirect",
                      "location": "http://isitthef5.com/"
                    }
                  ]
                }
              ]
            },
            "waf_pool": {
              "class": "Pool",
              "monitors": [
                "http"
              ],
              "members": [
                {
                  "servicePort": 80,
                  "serverAddresses": []
                }
              ]
            },
            "OWASPAutoTune": {
              "class": "WAF_Policy",
              "url": "https://raw.githubusercontent.com/mdditt2000/f5-as3-declarations/master/Common_WAF_Policy.xml",
              "ignoreChanges": true
            }
          }
        }
      }
    }
