kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-hello-world
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.10.0",
        "label": "Sample 1",
        "remark": "Simple HTTP application with RR pool",
        "AS3": {
          "class": "Tenant",
          "A1": {
            "class": "Application",
            "template": "http",
            "serviceMain": {
              "class": "Service_HTTP",
              "virtualAddresses": [
                "1.1.1.1"
              ],
              "pool": "web_pool",
              "securityLogProfiles": [
                    {
                        "bigip": "/Common/Log all requests"
                    }
                ],
                "policyWAF": {
                    "use": "owaspautotune"
                }
            },
            "web_pool": {
              "class": "Pool",
              "monitors": [
                "http"
              ],
              "members": [
                {
                  "servicePort": 80,
                  "serverAddresses": []
                }
              ]
            },
            "owaspautotune": {
                "class": "WAF_Policy",
                "url": "https://raw.githubusercontent.com/mdditt2000/f5-as3-declarations/master/Common_WAF_Policy.xml",
                "ignoreChanges": true
            }
          }
        }
      }
    }
