apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5-hello-world
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5-hello-world
  template:
    metadata:
      labels:
        app: f5-hello-world
    spec:
      containers:
      - env:
        - name: service_name
          value: f5-hello-world
        image: f5networksdevel/test-nginx:latest
        imagePullPolicy: Always
        name: f5-hello-world
        ports:
        - containerPort: 80
          protocol: TCP