kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-hello-world-https
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.10.0",
        "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
        "label": "Sample 2",
        "remark": "Simple HTTPS application with RR pool",
        "AS3": {
          "class": "Tenant",
          "A2": {
            "class": "Application",
            "template": "https",
            "serviceMain": {
              "class": "Service_HTTPS",
              "virtualAddresses": [
                "1.1.1.2"
              ],
              "pool": "secure_pool",
              "serverTLS": "webtls"
            },
            "secure_pool": {
              "class": "Pool",
              "loadBalancingMode": "predictive-node",
              "monitors": [
                "http"
              ],
              "members": [
                {
                  "servicePort": 80,
                  "serverAddresses": []
                }
              ]
            },
            "webtls": {
              "class": "TLS_Server",
              "certificates": [
                {
                  "certificate": "webcert"
                }
              ]
            },
            "webcert": {
              "class": "Certificate",
              "certificate": {
                "bigip": "/Common/default.crt"
              },
              "privateKey": {
                "bigip": "/Common/default.key"
              }
            }
          }
        }
      }
    }